# The URL the site will be built for
base_url = "https://ccydtn.github.io"
title = "CcydtN"
description = "Not showing up on the page"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true

theme = "apollo"

taxonomies = [{ name = "tags" }]

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
toc = true
use_cdn = false
favicon = "themes/apollo/icon/favicon.png"
theme = "toggle"
comment = false
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  # { name = "/projects", url = "/projects", weight = 2 },
  { name = "/about", url = "/about", weight = 3 },
  { name = "/tags", url = "/tags", weight = 4 },
]
socials = [
  { name = "github", url = "https://github.com/CcydtN/", icon = "github" },
]

custom_css = []

# To add google analytics
[extra.analytics]
enabled = false
